In [1]:
#https://stackoverflow.com/questions/22923775/calculate-pandas-dataframe-time-difference-between-two-columns-in-hours-and-minu

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(columns=['to','fr','ans'])
df

Empty DataFrame
Columns: [to, fr, ans]
Index: []

In [21]:
df.to = [pd.Timestamp('2015-01-24 13:03:12.050000'), pd.Timestamp('2015-01-27 11:57:18.240000'), pd.Timestamp('2015-01-23 10:07:47.660000')]
df.fr = [pd.Timestamp('2014-01-26 23:41:21.870000'), pd.Timestamp('2014-01-27 15:38:22.540000'), pd.Timestamp('2014-01-23 18:50:41.420000')]

In [22]:
df

to                      fr  ans
0 2015-01-24 13:03:12.050 2014-01-26 23:41:21.870  NaN
1 2015-01-27 11:57:18.240 2014-01-27 15:38:22.540  NaN
2 2015-01-23 10:07:47.660 2014-01-23 18:50:41.420  NaN

In [23]:
(df.to - df.fr).astype('timedelta64[h]')

0    8701.0
1    8756.0
2    8751.0
dtype: float64

In [32]:
(df.to - df.fr).astype('timedelta64[h]')/np.timedelta64(1, 'M')

TypeError: ufunc true_divide cannot use operands with types dtype('float64') and dtype('<m8[M]')

In [24]:
import numpy as np

In [28]:
(df.to - df.fr)/np.timedelta64(1, 'M').astype(int)

0   362 days 13:21:50.180000
1   364 days 20:18:55.700000
2   364 days 15:17:06.240000
dtype: timedelta64[ns]

In [33]:
(df.to - df.fr)/np.timedelta64(1,'D')

0    362.556831
1    364.846478
2    364.636878
dtype: float64

In [36]:
(df.to - df.fr)/np.timedelta64(1,'M')

0    11.911763
1    11.986989
2    11.980102
dtype: float64

In [37]:
#https://www.marsja.se/python-pandas-groupby-tutorial-examples/
#groupby

In [39]:
data_url = 'http://vincentarelbundock.github.io/Rdatasets/csv/carData/Salaries.csv'
df = pd.read_csv(data_url, index_col = 0)
df.head()

rank discipline  yrs.since.phd  yrs.service   sex  salary
1      Prof          B             19           18  Male  139750
2      Prof          B             20           16  Male  173200
3  AsstProf          B              4            3  Male   79750
4      Prof          B             45           39  Male  115000
5      Prof          B             40           41  Male  141500

In [40]:
df.shape

(397, 6)

In [42]:
df_rank = df.groupby('rank')

In [43]:
df_rank.count()

discipline  yrs.since.phd  yrs.service  sex  salary
rank                                                          
AssocProf          64             64           64   64      64
AsstProf           67             67           67   67      67
Prof              266            266          266  266     266

In [44]:
df_rank.size()

rank
AssocProf     64
AsstProf      67
Prof         266
dtype: int64

In [45]:
df_rank.nunique()

rank  discipline  yrs.since.phd  yrs.service  sex  salary
rank                                                                
AssocProf     1           2             24           21    2      63
AsstProf      1           2             11            7    2      53
Prof          1           2             42           50    2     261

In [46]:
df_rank['salary'].mean()

rank
AssocProf     93876.437500
AsstProf      80775.985075
Prof         126772.109023
Name: salary, dtype: float64

In [47]:
df_rank['salary'].mean().reset_index()

rank         salary
0  AssocProf   93876.437500
1   AsstProf   80775.985075
2       Prof  126772.109023

In [48]:
# https://stackoverflow.com/questions/48870463/pd-to-datetime-is-getting-half-my-dates-with-flipped-day-months

In [49]:
import pandas as pd

In [50]:
df = pd.DataFrame(
    {'Date': ['01/03/2018', '06/08/2018', '31/03/2018', '30/04/2018']}
)

df

Date
0  01/03/2018
1  06/08/2018
2  31/03/2018
3  30/04/2018

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
Date    4 non-null object
dtypes: object(1)
memory usage: 112.0+ bytes


In [52]:
date_parts = df['Date'].apply(lambda d: pd.Series(int(n) for n in d.split('/')))
date_parts

0  1     2
0   1  3  2018
1   6  8  2018
2  31  3  2018
3  30  4  2018

In [54]:
date_parts.columns = ['day', 'month', 'year']
date_parts

day  month  year
0    1      3  2018
1    6      8  2018
2   31      3  2018
3   30      4  2018

In [55]:
pd.to_datetime(date_parts)

0   2018-03-01
1   2018-08-06
2   2018-03-31
3   2018-04-30
dtype: datetime64[ns]

In [56]:
# https://chrisalbon.com/python/data_wrangling/pandas_join_merge_dataframe/
# join and merge pandas datafarme

In [57]:
import pandas as pd
from IPython.display import display
from IPython.display import Image

In [58]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
df_a = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_a

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [59]:
raw_data = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
df_b = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_b

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [60]:
df_new = pd.concat([df_a, df_b])
df_new

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [62]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
df_n = pd.DataFrame(raw_data, columns = ['subject_id','test_id'])
df_n

subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [65]:
df_6 = pd.merge(df_new, df_n, on = 'subject_id')
df_6

subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          4      Billy    Bonder       61
5          5     Ayoung   Atiches       16
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

In [64]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [67]:
df_6[['first_name', 'last_name']].apply(le.fit_transform)

first_name  last_name
0           0          2
1           3          0
2           2          1
3           1          3
4           6          6
5           4          4
6           7          5
7           8          7
8           5          8

In [72]:
dict_data = {'Treatment': ['C', 'C', 'C'], 'Biorep': ['A', 'A', 'A'], 'Techrep': [1, 1, 1], 'AAseq': ['ELVISLIVES', 'ELVISLIVES', 'ELVISLIVES'], 'mz':[500.0, 500.5, 501.0]}
df_a = pd.DataFrame(dict_data)
dict_data = {'Treatment': ['C', 'C', 'C'], 'Biorep': ['A', 'A', 'A'], 'Techrep': [1, 1, 1], 'AAseq': ['ELVISLIVES', 'ELVISLIVES', 'ELVISLIVES'], 'mz':[1100.0, 1050.0, 1010.0]}
df_b = pd.DataFrame(dict_data)

In [73]:
df_a

Treatment Biorep  Techrep       AAseq     mz
0         C      A        1  ELVISLIVES  500.0
1         C      A        1  ELVISLIVES  500.5
2         C      A        1  ELVISLIVES  501.0

In [74]:
df_b

Treatment Biorep  Techrep       AAseq      mz
0         C      A        1  ELVISLIVES  1100.0
1         C      A        1  ELVISLIVES  1050.0
2         C      A        1  ELVISLIVES  1010.0

In [75]:
pd.concat([df_a, df_b], axis = 0)

Treatment Biorep  Techrep       AAseq      mz
0         C      A        1  ELVISLIVES   500.0
1         C      A        1  ELVISLIVES   500.5
2         C      A        1  ELVISLIVES   501.0
0         C      A        1  ELVISLIVES  1100.0
1         C      A        1  ELVISLIVES  1050.0
2         C      A        1  ELVISLIVES  1010.0

In [77]:
# label encoding for categorucal variabels
# https://code.i-harness.com/en/q/231a6f2

In [78]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [80]:
a = pd.DataFrame(['A','B','C',np.nan,'D','A'])
print(a)

     0
0    A
1    B
2    C
3  NaN
4    D
5    A


In [81]:
le = LabelEncoder()

In [96]:
a.apply(lambda x: le.fit_transform(x) if not np.isnan(x) else x)

TypeError: ("ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''", 'occurred at index 0')

In [89]:
np.isnan(np.nan)

True

In [94]:
np.isnan(np.nan)

True

In [95]:
not np.isnan(np.nan)

False

In [99]:
np.isnan(1)

False

In [100]:
np.isnan('A')

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [102]:
pd.isnull(a)

0
0  False
1  False
2  False
3   True
4  False
5  False

In [104]:
fit_by = [i for i in a.iloc[:,0].unique() if type(i) ==  str]
fit_by

['A', 'B', 'C', 'D']

In [105]:
le.fit(fit_by)

LabelEncoder()

In [106]:
b = fit_by.apply(lambda x: le.transform([x])[0] if type(x) == str else x)
b

AttributeError: 'list' object has no attribute 'apply'

In [107]:
df = pd.DataFrame({'A': ['x', np.NaN, 'z'], 'B': [1, 6, 9], 'C': [2, 1, np.NaN]})
print(df)

     A  B    C
0    x  1  2.0
1  NaN  6  1.0
2    z  9  NaN


In [109]:
mask = df.isnull()
mask

A      B      C
0  False  False  False
1   True  False  False
2  False  False   True

In [115]:
df = df.astype(str).apply(LabelEncoder().fit_transform)
df

A  B  C
0  1  0  1
1  0  1  0
2  2  2  2

In [116]:
df.where(~mask)

A  B    C
0  1.0  0  1.0
1  NaN  1  0.0
2  2.0  2  NaN

In [117]:
a = np.array([5,4,2,2,4,np.nan,np.nan,6])
a

array([ 5.,  4.,  2.,  2.,  4., nan, nan,  6.])

In [118]:
set(a)

{nan, nan, 2.0, 4.0, 5.0, 6.0}

In [119]:
np.isnan(a)

array([False, False, False, False, False,  True,  True, False])

In [120]:
a[~np.isnan(a)]

array([5., 4., 2., 2., 4., 6.])

In [121]:
np.unique(a[~np.isnan(a)])

array([2., 4., 5., 6.])

In [122]:
set(a[~np.isnan(a)])

{2.0, 4.0, 5.0, 6.0}

In [123]:
my_list =  ['apple', 'banana', 'grapes', 'pear']
my_list

['apple', 'banana', 'grapes', 'pear']

In [124]:
for c, value in enumerate(my_list, 1):
    print(c, value)

1 apple
2 banana
3 grapes
4 pear


In [127]:
seasons = ['Spring', 'Summer', 'Fall', 'Winter', 'Spring']

In [128]:
list(enumerate(seasons))

[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter'), (4, 'Spring')]

In [130]:
seasons = ['Spring', 'Summer', 'Fall', 'Winter']

season_dict = {i: seasons[i] for i in range(0, len(seasons))}
season_dict

{0: 'Spring', 1: 'Summer', 2: 'Fall', 3: 'Winter'}

In [131]:
season_dict_2 = {seasons[i]: i for i in range(0, len(seasons))}
season_dict_2

{'Spring': 0, 'Summer': 1, 'Fall': 2, 'Winter': 3}

In [132]:
# http://docs.w3cub.com/scikit_learn/modules/generated/sklearn.model_selection.groupkfold/
from sklearn.model_selection import GroupKFold

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])

groups = np.array([0,0,2,2])

In [134]:
groups

array([0, 0, 2, 2])

In [135]:
X

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
group_kfold = GroupKFold(n_splits = 2)

In [136]:
group_kfold.get_n_splits(X, y, groups)

2

In [138]:
print(group_kfold)

GroupKFold(n_splits=2)


In [140]:
list(group_kfold)

TypeError: 'GroupKFold' object is not iterable

In [141]:
list(GroupKFold(n_splits = 2).split(X, y, groups))

[(array([0, 1]), array([2, 3])), (array([2, 3]), array([0, 1]))]

In [144]:
for train_index, test_index in GroupKFold(n_splits = 2).split(X, y, groups):
    print('Train: ', train_index, 'Test: ', test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, y_train)
    print('######')
    print(X_test, y_test)

Train:  [0 1] Test:  [2 3]
[[1 2]
 [3 4]] [1 2]
######
[[5 6]
 [7 8]] [3 4]
Train:  [2 3] Test:  [0 1]
[[5 6]
 [7 8]] [3 4]
######
[[1 2]
 [3 4]] [1 2]


In [1]:
# https://towardsdatascience.com/the-dummys-guide-to-creating-dummy-variables-f21faddb1d40
# Dummy Variables

import pandas as pd

df = pd.read_table('http://data.princeton.edu/wws509/datasets/salary.dat', delim_whitespace = True)
df.head()

sx    rk  yr         dg  yd     sl
0    male  full  25  doctorate  35  36350
1    male  full  13  doctorate  22  35350
2    male  full  10  doctorate  23  28200
3  female  full   7  doctorate  27  26775
4    male  full  19    masters  30  33696

In [2]:
df.shape

(52, 6)

In [4]:
import numpy as np

col_num = np.arange(1, 53)
col_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52])

In [6]:
col_num = pd.DataFrame(col_num)
col_num

0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20
20  21
21  22
22  23
23  24
24  25
25  26
26  27
27  28
28  29
29  30
30  31
31  32
32  33
33  34
34  35
35  36
36  37
37  38
38  39
39  40
40  41
41  42
42  43
43  44
44  45
45  46
46  47
47  48
48  49
49  50
50  51
51  52

In [8]:
df_2 = pd.concat([df, col_num], axis = 1)
df_2

sx         rk  yr         dg  yd     sl   0
0     male       full  25  doctorate  35  36350   1
1     male       full  13  doctorate  22  35350   2
2     male       full  10  doctorate  23  28200   3
3   female       full   7  doctorate  27  26775   4
4     male       full  19    masters  30  33696   5
5     male       full  16  doctorate  21  28516   6
6   female       full   0    masters  32  24900   7
7     male       full  16  doctorate  18  31909   8
8     male       full  13    masters  30  31850   9
9     male       full  13    masters  31  32850  10
10    male       full  12  doctorate  22  27025  11
11    male  associate  15  doctorate  19  24750  12
12    male       full   9  doctorate  17  28200  13
13    male  associate   9    masters  27  23712  14
14    male       full   9  doctorate  24  25748  15
15    male       full   7  doctorate  15  29342  16
16    male       full  13  doctorate  20  31114  17
17    male  associate  11    masters  14  24742  18
18    male  associate  10    masters  15  22906  19
19    male       full   6    masters  21  24450  20
20    male  assistant  16    masters  23  19175  21
21    male  associate   8    masters  31  20525  22
22    male       full   7  doctorate  13  27959  23
23  female       full   8  doctorate  24  38045  24
24    male  associate   9  doctorate  12  24832  25
25    male       full   5  doctorate  18  25400  26
26    male  associate  11  doctorate  14  24800  27
27  female       full   5  doctorate  16  25500  28
28    male  associate   3    masters   7  26182  29
29    male  associate   3    masters  17  23725  30
30  female  assistant  10    masters  15  21600  31
31    male  associate  11    masters  31  23300  32
32    male  assistant   9    masters  14  23713  33
33  female  associate   4    masters  33  20690  34
34  female  associate   6    masters  29  22450  35
35    male  associate   1  doctorate   9  20850  36
36  female  assistant   8  doctorate  14  18304  37
37    male  assistant   4  doctorate   4  17095  38
38    male  assistant   4  doctorate   5  16700  39
39    male  assistant   4  doctorate   4  17600  40
40    male  assistant   3  doctorate   4  18075  41
41    male  assistant   3    masters  11  18000  42
42    male  associate   0  doctorate   7  20999  43
43  female  assistant   3  doctorate   3  17250  44
44    male  assistant   2  doctorate   3  16500  45
45    male  assistant   2  doctorate   1  16094  46
46  female  assistant   2  doctorate   6  16150  47
47  female  assistant   2  doctorate   2  15350  48
48    male  assistant   1  doctorate   1  16244  49
49  female  assistant   1  doctorate   1  16686  50
50  female  assistant   1  doctorate   1  15000  51
51  female  assistant   0  doctorate   2  20300  52

In [9]:
pd.get_dummies(df_2)

yr  yd     sl   0  sx_female  sx_male  rk_assistant  rk_associate  \
0   25  35  36350   1          0        1             0             0   
1   13  22  35350   2          0        1             0             0   
2   10  23  28200   3          0        1             0             0   
3    7  27  26775   4          1        0             0             0   
4   19  30  33696   5          0        1             0             0   
5   16  21  28516   6          0        1             0             0   
6    0  32  24900   7          1        0             0             0   
7   16  18  31909   8          0        1             0             0   
8   13  30  31850   9          0        1             0             0   
9   13  31  32850  10          0        1             0             0   
10  12  22  27025  11          0        1             0             0   
11  15  19  24750  12          0        1             0             1   
12   9  17  28200  13          0        1             0             0   
13   9  27  23712  14          0        1             0             1   
14   9  24  25748  15          0        1             0             0   
15   7  15  29342  16          0        1             0             0   
16  13  20  31114  17          0        1             0             0   
17  11  14  24742  18          0        1             0             1   
18  10  15  22906  19          0        1             0             1   
19   6  21  24450  20          0        1             0             0   
20  16  23  19175  21          0        1             1             0   
21   8  31  20525  22          0        1             0             1   
22   7  13  27959  23          0        1             0             0   
23   8  24  38045  24          1        0             0             0   
24   9  12  24832  25          0        1             0             1   
25   5  18  25400  26          0        1             0             0   
26  11  14  24800  27          0        1             0             1   
27   5  16  25500  28          1        0             0             0   
28   3   7  26182  29          0        1             0             1   
29   3  17  23725  30          0        1             0             1   
30  10  15  21600  31          1        0             1             0   
31  11  31  23300  32          0        1             0             1   
32   9  14  23713  33          0        1             1             0   
33   4  33  20690  34          1        0             0             1   
34   6  29  22450  35          1        0             0             1   
35   1   9  20850  36          0        1             0             1   
36   8  14  18304  37          1        0             1             0   
37   4   4  17095  38          0        1             1             0   
38   4   5  16700  39          0        1             1             0   
39   4   4  17600  40          0        1             1             0   
40   3   4  18075  41          0        1             1             0   
41   3  11  18000  42          0        1             1             0   
42   0   7  20999  43          0        1             0             1   
43   3   3  17250  44          1        0             1             0   
44   2   3  16500  45          0        1             1             0   
45   2   1  16094  46          0        1             1             0   
46   2   6  16150  47          1        0             1             0   
47   2   2  15350  48          1        0             1             0   
48   1   1  16244  49          0        1             1             0   
49   1   1  16686  50          1        0             1             0   
50   1   1  15000  51          1        0             1             0   
51   0   2  20300  52          1        0             1             0   

    rk_full  dg_doctorate  dg_masters  
0         1             1           0  
1         1             1           0  
2         1   

In [10]:
# rename column names
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df

A  B
0  1  4
1  2  5
2  3  6

In [11]:
df.columns.values

array(['A', 'B'], dtype=object)

In [1]:
# https://github.com/Microsoft/LightGBM/issues/1020
# LightGBM for categorical features

In [5]:
import pandas as pd
import numpy as np

In [6]:
X = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'c', 'd'] * 75),  # str 
                       "B": np.random.permutation([1, 2, 3] * 100),  # int 
                       "C": np.random.permutation([0.1, 0.2, -0.1, -0.1, 0.2] * 60),  # float 
                       "D": np.random.permutation([True, False] * 150)})

y = np.random.permutation([0, 1] * 150)

X_test = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'e'] * 20), 
                            "B": np.random.permutation([1, 3] * 30), 
                            "C": np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), 
                            "D": np.random.permutation([True, False] * 30)}) 

In [8]:
X.head()

A  B    C      D
0  d  1 -0.1   True
1  d  2 -0.1  False
2  b  1  0.1   True
3  a  3 -0.1  False
4  a  3  0.2   True

In [9]:
X.dtypes

A     object
B      int32
C    float64
D       bool
dtype: object

In [10]:
print(X.shape)
print(X_test.shape)
print(len(y))

(300, 4)
(60, 4)
300


In [22]:
for col in ['A', 'B', 'C', 'D']:
    X[col] = X[col].astype('category')
    X_test[col] = X_test[col].astype('category')

In [23]:
X.dtypes

A    category
B    category
C    category
D    category
dtype: object

In [14]:
y[:5]

array([0, 0, 1, 1, 0])

In [29]:
X = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'c', 'd'] * 75),  # str 
                       "B": np.random.permutation([1, 2, 3] * 100),  # int 
                       "C": np.random.permutation([0.1, 0.2, -0.1, -0.1, 0.2] * 60),  # float 
                       "D": np.random.permutation([True, False] * 150)})

y = np.random.permutation([0, 1] * 150)

X_test = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'e'] * 20), 
                            "B": np.random.permutation([1, 3] * 30), 
                            "C": np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), 
                            "D": np.random.permutation([True, False] * 30)}) 

In [30]:
import lightgbm as lgb

In [44]:
params_ = {'objective': 'binary',
          'metric': 'binary_logloss',
          'verbose': -1}

In [45]:
 for col in ["A", "B", "C", "D"]:
            X[col] = X[col].astype('category')
            X_test[col] = X_test[col].astype('category')

In [46]:
lgb_train = lgb.Dataset(X, label = y)

In [47]:
gbm0 = lgb.train(params_, 
                 lgb_train, 
                 num_boost_round=10, 
                 verbose_eval=True)

In [40]:
mod_lgb = lgb.train(params = params_,
                     lgb_train,
                     num_boost_round = 10,
                     verbose_eval = False)

SyntaxError: positional argument follows keyword argument (<ipython-input-40-e1d20dcbe4a1>, line 2)

In [41]:
X = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'c', 'd'] * 75),  # str 
                       "B": np.random.permutation([1, 2, 3] * 100),  # int 
                       "C": np.random.permutation([0.1, 0.2, -0.1, -0.1, 0.2] * 60),  # float 
                       "D": np.random.permutation([True, False] * 150)})

y = np.random.permutation([0, 1] * 150)

X_test = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'e'] * 20), 
                            "B": np.random.permutation([1, 3] * 30), 
                            "C": np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), 
                            "D": np.random.permutation([True, False] * 30)}) 

In [42]:
lgb_train = lgb.Dataset(X, label = y)

In [43]:
gbm0 = lgb.train(params_, 
                 lgb_train, 
                 num_boost_round=10, 
                 verbose_eval=True)

ValueError: DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in fields A

In [48]:
for col in ["A", "B", "C", "D"]:
            X[col] = X[col].astype('category')
            X_test[col] = X_test[col].astype('category')

In [49]:
X.dtypes

A    category
B    category
C    category
D    category
dtype: object

In [55]:
gbm0 = lgb.train(params_, 
                 lgb_train, 
                 num_boost_round=10, 
                 verbose_eval=True)

In [60]:
gbm1 = lgb.train(params_,
                 lgb_train,
                 10,
                #'num_boost_round = 10,
                verbose_eval = True)

In [61]:
gbm2 = lgb.train(#params_,
                 lgb_train,
                params_,
                 10,
                #'num_boost_round = 10,
                verbose_eval = True)

ValueError: ctypes objects containing pointers cannot be pickled

In [52]:
X

A  B    C      D
0    c  3  0.2  False
1    d  3  0.2  False
2    b  2 -0.1  False
3    b  2 -0.1   True
4    b  1 -0.1   True
5    c  3  0.1   True
6    b  3 -0.1  False
7    a  1 -0.1  False
8    b  2 -0.1   True
9    a  3 -0.1  False
10   a  3  0.2   True
11   c  2 -0.1   True
12   c  2  0.1  False
13   c  2  0.2  False
14   a  3  0.2   True
15   b  1  0.2  False
16   c  1  0.2  False
17   a  2 -0.1   True
18   b  2  0.2  False
19   d  1 -0.1   True
20   a  2  0.1  False
21   d  1 -0.1  False
22   d  3 -0.1  False
23   c  3 -0.1   True
24   d  3  0.2   True
25   a  2 -0.1  False
26   b  3  0.2   True
27   b  3  0.2  False
28   a  3 -0.1  False
29   b  2  0.2   True
..  .. ..  ...    ...
270  a  3  0.2   True
271  b  1  0.2   True
272  a  3  0.2  False
273  d  2 -0.1   True
274  c  3  0.2  False
275  d  1 -0.1  False
276  c  3  0.1   True
277  a  1  0.1  False
278  d  1 -0.1  False
279  d  1  0.1   True
280  b  1  0.2   True
281  c  3  0.2  False
282  a  2 -0.1  False
283  d  1 -0.1  False
284  a  3  0.1  False
285  d  2  0.2  False
286  c  1  0.1   True
287  a  1 -0.1   True
288  c  3 -0.1  False
289  a  1 -0.1  False
290  b  1 -0.1   True
291  a  3  0.1  False
292  c  2  0.2   True
293  b  1  0.1   True
294  c  2  0.1   True
295  d  3 -0.1   True
296  b  2  0.2   True
297  b  3 -0.1   True
298  c  3 -0.1  False
299  c  2  0.1   True

[300 rows x 4 columns]

In [62]:
X = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'c', 'd'] * 75),  # str 
                       "B": np.random.permutation([1, 2, 3] * 100),  # int 
                       "C": np.random.permutation([0.1, 0.2, -0.1, -0.1, 0.2] * 60),  # float 
                       "D": np.random.permutation([True, False] * 150)})

y = np.random.permutation([0, 1] * 150)

X_test = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'e'] * 20), 
                            "B": np.random.permutation([1, 3] * 30), 
                            "C": np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), 
                            "D": np.random.permutation([True, False] * 30)}, dtype='category')

In [63]:
X.dtypes

A     object
B      int32
C    float64
D       bool
dtype: object

In [64]:
lgb_train = lgb.Dataset(X, label = y)

In [65]:
gbm1 = lgb.train(params_,
                 lgb_train,
                 10,
                #'num_boost_round = 10,
                verbose_eval = True)

ValueError: DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in fields A

In [66]:
X = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'c', 'd'] * 75),  # str 
                       "B": np.random.permutation([1, 2, 3] * 100),  # int 
                       "C": np.random.permutation([0.1, 0.2, -0.1, -0.1, 0.2] * 60),  # float 
                       "D": np.random.permutation([True, False] * 150)})

y = np.random.permutation([0, 1] * 150)

X_test = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'e'] * 20), 
                            "B": np.random.permutation([1, 3] * 30), 
                            "C": np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), 
                            "D": np.random.permutation([True, False] * 30)}, dtype='category')

In [79]:
X_test = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'e'] * 20), 
                            "B": np.random.permutation([1, 3] * 30), 
                            "C": np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), 
                            "D": np.random.permutation([True, False] * 30)}, dtype='category')

In [80]:
X_test.dtypes

A    category
B    category
C    category
D    category
dtype: object

In [67]:
X.dtypes

A     object
B      int32
C    float64
D       bool
dtype: object

In [85]:
X_test = pd.DataFrame({"A": np.array(np.random.permutation(['a', 'b', 'e'] * 20), dtype=str), 
                            "B": np.array(np.random.permutation([1, 3] * 30), dtype=int), 
                            "C": np.array(np.random.permutation([0.1, -0.1, 0.2, 0.2] * 15), dtype = float), 
                            "D": np.array(np.random.permutation([True, False] * 30), dtype = bool)})

In [87]:
X_test.dtypes

A     object
B      int32
C    float64
D       bool
dtype: object

In [91]:
X_test['A'] = X_test['A'].astype('category', inplace = True)

In [92]:
X_test.dtypes

A    category
B       int32
C     float64
D        bool
dtype: object

In [95]:
X['A'] = X['A'].astype('category')

In [96]:
X.dtypes

A    category
B       int32
C     float64
D        bool
dtype: object

In [98]:
lgb_train = lgb.Dataset(X, label = y)

In [99]:
gbm5 = lgb.train(params_,
                 lgb_train,
                num_boost_round = 10,
                verbose_eval = True)

In [100]:
gbm5

In [101]:
# Quick start
# https://tech.yandex.com/catboost/doc/dg/concepts/python-quickstart-docpage/

In [109]:
import numpy as np
from catboost import CatBoostClassifier, Pool

train_data = np.random.randint(0, 100, size = (100, 10))
train_labels = np.random.randint(0, 2, size = (100))

test_data_1 = np.random.randint(0, 100, size = (50, 10))

In [110]:
train_data[:5]

array([[28, 68, 75, 41, 14, 89, 26, 53, 47, 89],
       [57, 73, 66, 69, 38, 13, 40, 21, 63, 36],
       [30, 76, 52, 43, 62, 40, 83, 61, 88, 78],
       [53, 41, 63, 80, 47, 58, 45, 29,  0, 36],
       [74, 41, 83, 41,  7, 12, 50, 12, 95, 70]])

In [111]:
test_data = catboost_pool = Pool(train_data,
                                train_labels)

In [113]:
train_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1])

In [115]:
mod_1 = CatBoostClassifier(iterations = 100,
                          depth = 2,
                          learning_rate = 0.01,
                          loss_function = 'Logloss',
                          logging_level = 'Verbose')

In [116]:
mod_1.fit(train_data, train_labels)

0:	learn: 0.6921084	total: 90.1ms	remaining: 8.92s
1:	learn: 0.6912774	total: 120ms	remaining: 5.9s
2:	learn: 0.6906074	total: 150ms	remaining: 4.86s
3:	learn: 0.6896428	total: 196ms	remaining: 4.7s
4:	learn: 0.6887135	total: 228ms	remaining: 4.33s
5:	learn: 0.6879790	total: 257ms	remaining: 4.03s
6:	learn: 0.6872657	total: 283ms	remaining: 3.76s
7:	learn: 0.6865085	total: 305ms	remaining: 3.5s
8:	learn: 0.6862535	total: 325ms	remaining: 3.28s
9:	learn: 0.6858563	total: 354ms	remaining: 3.18s
10:	learn: 0.6850693	total: 373ms	remaining: 3.02s
11:	learn: 0.6845747	total: 392ms	remaining: 2.87s
12:	learn: 0.6833696	total: 405ms	remaining: 2.71s
13:	learn: 0.6830542	total: 418ms	remaining: 2.57s
14:	learn: 0.6819922	total: 433ms	remaining: 2.45s
15:	learn: 0.6816270	total: 447ms	remaining: 2.35s
16:	learn: 0.6806353	total: 462ms	remaining: 2.25s
17:	learn: 0.6804064	total: 477ms	remaining: 2.17s
18:	learn: 0.6797248	total: 491ms	remaining: 2.09s
19:	learn: 0.6791473	total: 504ms	remaining

In [117]:
preds_class = mod_1.predict(test_data)
print(preds_class)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0.
 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.
 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1.
 1. 0. 1. 1.]


In [118]:
pred_proba = mod_1.predict_proba(test_data)
pred_proba

array([[0.45775963, 0.54224037],
       [0.44759953, 0.55240047],
       [0.48692725, 0.51307275],
       [0.46100989, 0.53899011],
       [0.44084328, 0.55915672],
       [0.45765736, 0.54234264],
       [0.49344368, 0.50655632],
       [0.44221182, 0.55778818],
       [0.41615691, 0.58384309],
       [0.4945937 , 0.5054063 ],
       [0.44919401, 0.55080599],
       [0.50948188, 0.49051812],
       [0.55697492, 0.44302508],
       [0.48330413, 0.51669587],
       [0.56194654, 0.43805346],
       [0.55636642, 0.44363358],
       [0.5160996 , 0.4839004 ],
       [0.53172866, 0.46827134],
       [0.5793348 , 0.4206652 ],
       [0.4238365 , 0.5761635 ],
       [0.45325286, 0.54674714],
       [0.56526447, 0.43473553],
       [0.47710778, 0.52289222],
       [0.53876223, 0.46123777],
       [0.40619714, 0.59380286],
       [0.44498096, 0.55501904],
       [0.40679947, 0.59320053],
       [0.56002798, 0.43997202],
       [0.48988672, 0.51011328],
       [0.50059266, 0.49940734],
       [0.

In [119]:
# CatBoost Regressor

import numpy as np
from catboost import Pool, CatBoostRegressor

train_data = np.random.randint(0, 100, size = (100, 10))
train_label = np.random.randint(0, 1000, size = (100))
test_data = np.random.randint(0, 100, size = (50, 10))

In [120]:
train_pool = Pool(train_data,
                train_label,
                cat_features = [0,2,5])

test_pool = Pool(test_data,
                cat_features = [0,2,5])

In [121]:
mod_2 = CatBoostRegressor(iterations = 100,
                         depth = 2,
                         learning_rate = 0.01,
                         loss_function = 'RMSE')

In [122]:
mod_2.fit(train_pool)

0:	learn: 569.1104243	total: 31ms	remaining: 3.07s
1:	learn: 564.9728039	total: 50.3ms	remaining: 2.46s
2:	learn: 560.9575339	total: 72.6ms	remaining: 2.35s
3:	learn: 556.9987030	total: 106ms	remaining: 2.55s
4:	learn: 552.9701252	total: 130ms	remaining: 2.47s
5:	learn: 549.0262125	total: 162ms	remaining: 2.53s
6:	learn: 545.1373531	total: 188ms	remaining: 2.5s
7:	learn: 541.3981599	total: 210ms	remaining: 2.41s
8:	learn: 537.4974890	total: 231ms	remaining: 2.33s
9:	learn: 533.7493770	total: 251ms	remaining: 2.26s
10:	learn: 530.0272227	total: 269ms	remaining: 2.18s
11:	learn: 526.3944364	total: 286ms	remaining: 2.1s
12:	learn: 522.7384286	total: 304ms	remaining: 2.03s
13:	learn: 519.2317060	total: 323ms	remaining: 1.98s
14:	learn: 515.7302321	total: 341ms	remaining: 1.93s
15:	learn: 512.1372660	total: 361ms	remaining: 1.89s
16:	learn: 508.7333664	total: 377ms	remaining: 1.84s
17:	learn: 505.2054464	total: 398ms	remaining: 1.81s
18:	learn: 501.8128941	total: 420ms	remaining: 1.79s
19:	

In [124]:
preds = mod_2.predict(test_pool)
print(preds)

[319.98740864 290.90113313 313.27656926 308.46091497 307.34551282
 295.29150554 299.91992737 306.40025353 288.65814992 290.75233311
 312.50064599 297.17931661 316.1340305  306.81015302 303.99994961
 306.22776972 319.76232548 314.38192685 305.73253677 309.14353998
 306.79741018 310.19454992 305.26631135 307.45532828 297.0822352
 299.80199742 301.36575478 306.42814388 305.01539358 291.92743398
 319.53160738 317.39082081 304.34584478 305.61940887 312.29062375
 322.2385493  315.23040608 301.27968407 317.25548488 307.38983268
 308.08114367 308.8975799  296.03460009 299.26007138 310.16071356
 294.41728947 305.0779741  308.21979848 300.20636158 296.54051079]


In [126]:
import numpy as np
from catboost import CatBoostClassifier, FeaturesData, Pool

train_data = Pool(
    data=FeaturesData(
        num_feature_data=np.array([[1, 4, 5, 6], 
                                   [4, 5, 6, 7], 
                                   [30, 40, 50, 60]], 
                                   dtype=np.float32),
        cat_feature_data=np.array([["a", "b"], 
                                   ["a", "b"], 
                                   ["c", "d"]], 
                                   dtype=object)
    ),
    label=[1, 1, -1]
)

In [127]:
test_data = Pool(
    data=FeaturesData(
        num_feature_data=np.array([[2, 4, 6, 8], 
                                   [1, 4, 50, 60]], 
                                   dtype=np.float32),
        cat_feature_data=np.array([["a", "b"], 
                                   ["a", "d"]], 
                                   dtype=object)
    )
)

In [128]:
train_data

In [129]:
test_data

In [130]:
mod_3 = CatBoostClassifier(iterations = 100,
                          learning_rate = 0.01,
                          depth = 2,
                          loss_function = 'Logloss')

In [131]:
mod_3.fit(train_data)

0:	learn: 0.6875287	total: 28.2ms	remaining: 2.79s
1:	learn: 0.6800475	total: 57.6ms	remaining: 2.82s
2:	learn: 0.6745686	total: 84.3ms	remaining: 2.73s
3:	learn: 0.6672691	total: 114ms	remaining: 2.75s
4:	learn: 0.6600730	total: 140ms	remaining: 2.67s
5:	learn: 0.6548067	total: 166ms	remaining: 2.61s
6:	learn: 0.6477850	total: 201ms	remaining: 2.67s
7:	learn: 0.6408627	total: 224ms	remaining: 2.58s
8:	learn: 0.6358005	total: 245ms	remaining: 2.48s
9:	learn: 0.6290456	total: 268ms	remaining: 2.41s
10:	learn: 0.6241085	total: 290ms	remaining: 2.34s
11:	learn: 0.6175168	total: 309ms	remaining: 2.27s
12:	learn: 0.6110181	total: 332ms	remaining: 2.22s
13:	learn: 0.6062715	total: 360ms	remaining: 2.21s
14:	learn: 0.5999293	total: 380ms	remaining: 2.15s
15:	learn: 0.5936764	total: 395ms	remaining: 2.07s
16:	learn: 0.5921829	total: 410ms	remaining: 2s
17:	learn: 0.5860406	total: 425ms	remaining: 1.94s
18:	learn: 0.5799845	total: 449ms	remaining: 1.91s
19:	learn: 0.5740133	total: 465ms	remaini

In [134]:
preds_class = mod_3.predict(test_data)
print(preds_class)

[1. 1.]


In [135]:
preds_proba = mod_3.predict_proba(test_data)
print(preds_class)

[1. 1.]


In [1]:
#https://xgboost.readthedocs.io/en/latest/tutorials/dart.html 

In [4]:
import xgboost as xgb
import numpy as np 
import pandas as pd

In [5]:
train = pd.read_pickle('train_2.pkl')
test = pd.read_pickle('test_2.pkl')

In [6]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  ...   cabin_binary family_size  solo  \
0      0         A/5 21171   7.2500  ...              0           2     0   
1      0          PC 17599  71.2833  ...              1           2     0   
2      0  STON/O2. 3101282   7.9250  ...              0           1     1   
3      0            113803  53.1000  ...              1           2     0   
4      0            373450   8.0500  ...              0           1     1   

   Child  toddler  Elderly  fancy  standard_fare  fare_std  title  
0      0        0        0      0              1 -0.502445     Mr  
1      0        0        0      0              0  0.786845     Ms  
2      0        0        0      0              1 -0.488854     Ms  
3      0        0        0      0              0  0.420730     Ms  
4      0        0        0      0              1 -0.486337     Mr  

[5 rows x 22 columns]

In [7]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin  ...   cabin_binary  \
0  34.5      0      0   330911   7.8292   NaN  ...              0   
1  47.0      1      0   363272   7.0000   NaN  ...              0   
2  62.0      0      0   240276   9.6875   NaN  ...              0   
3  27.0      0      0   315154   8.6625   NaN  ...              0   
4  22.0      1      1  3101298  12.2875   NaN  ...              0   

   family_size  solo  Child  toddler  Elderly  fancy  standard_fare  fare_std  \
0            1     1      0        0        0      0              1 -0.490783   
1            2     0      0        0        0      0              1 -0.507479   
2            1     1      0        0        1      0              1 -0.453367   
3            1     1      0        0        0      0              1 -0.474005   
4            3     0      0        0        0      0              0 -0.401017   

   title  
0     Mr  
1     Ms  
2     Mr  
3     Mr  
4     Ms  

[5 rows x 21 columns]

In [8]:
train = pd.get_dummies(train, columns = ['Sex', 'Embarked', 'title'])
test = pd.get_dummies(test, columns = ['Sex', 'Embarked', 'title'])

train = train.drop(['Name', 'PassengerId', 'Ticket', 'Cabin', 'Fare', 'SibSp'], axis = 1)
test = test.drop(['Name', 'PassengerId', 'Cabin', 'Fare', 'SibSp'], axis = 1)

In [9]:
X = train.drop(['Survived'], axis = 1)
y = train['Survived']

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [12]:
dtrain = xgb.DMatrix(X_train, label = y_train)
dtest = xgb.DMatrix(X_test, label = y_test)

In [13]:
#dtrain = xgb.DMatrix('demo/data/agaricus.txt.train')
#dtest = xgb.DMatrix('demo/data/agaricus.txt.test')

In [14]:
params_ = {'booster': 'dart',
          'max_depth': 5,
          'learning_rate': 0.01,
          'objective': 'binary:logistic',
          'silent': True,
          'sample_type': 'uniform',
          'normalize_type': 'tree',
          'rate_drop': 0.1,
          'skip_drop': 0.5}

In [15]:
num_round = 50

In [16]:
bst = xgb.train(params_,
               dtrain,
               num_round)

In [17]:
preds = bst.predict(dtest,
                   ntree_limit = num_round)
print(preds)

[0.36993346 0.36993346 0.36993346 0.6500201  0.52262646 0.6500201
 0.52262646 0.36993346 0.52262646 0.6500201  0.44571695 0.36993346
 0.37069303 0.36993346 0.36993346 0.6500201  0.43014866 0.52262646
 0.36993346 0.4243542  0.36993346 0.36993346 0.47020027 0.36993346
 0.36993346 0.4500805  0.36993346 0.36993346 0.4121068  0.47020027
 0.36993346 0.47020027 0.36993346 0.5091107  0.36993346 0.36993346
 0.44571695 0.52262646 0.6500201  0.36993346 0.39188364 0.36993346
 0.36993346 0.36993346 0.52262646 0.36993346 0.36993346 0.36993346
 0.36993346 0.47014964 0.61257863 0.6500201  0.36993346 0.44571695
 0.36993346 0.6500201  0.36993346 0.6500201  0.6500201  0.52262646
 0.36993346 0.6500201  0.6500201  0.36993346 0.36993346 0.6500201
 0.39188364 0.36993346 0.36993346 0.6500201  0.6500201  0.6500201
 0.5324479  0.6500201  0.36993346 0.36993346 0.52262646 0.6500201
 0.6500201  0.548419   0.36993346 0.6500201  0.6500201  0.36993346
 0.53079057 0.36993346 0.6500201  0.6500201  0.36993346 0.36993346

In [18]:
bst