In [1]:
import pandas as pd
import numpy as np

In [2]:
pp_data_all = pd.read_csv('pp_data_all.csv')
pp_data_train = pd.read_csv('pp_data_train.csv')

In [3]:
print(pp_data_all.shape)
print(pp_data_train.shape)

(289671, 64)
(145063, 65)


In [1]:
# pp_data_all.head()

In [2]:
# pp_data_train.head()

In [3]:
# pp_data_train.isnull().sum()/len(pp_data_train)

In [4]:
# pp_data_all.isnull().sum()/len(pp_data_all)

In [5]:
# pp_data_train.T

In [13]:
pd.to_datetime(pp_data_train['inc_datetime']).head()

0   2013-09-19 10:15:00
1   2013-09-19 10:15:00
2   2011-07-23 03:00:00
3   2011-07-23 03:00:00
4   2011-07-23 03:00:00
Name: inc_datetime, dtype: datetime64[ns]

In [15]:
pp_data_train['inc_datetime'] = pd.to_datetime(pp_data_train['inc_datetime'])
pp_data_train['inc_datetime'].head()

0   2013-09-19 10:15:00
1   2013-09-19 10:15:00
2   2011-07-23 03:00:00
3   2011-07-23 03:00:00
4   2011-07-23 03:00:00
Name: inc_datetime, dtype: datetime64[ns]

In [18]:
# generate new feature inc_hour

pp_data_train['inc_hour'] = pp_data_train['inc_datetime'].dt.hour
pp_data_train['inc_hour'].head()

0    10.0
1    10.0
2     3.0
3     3.0
4     3.0
Name: inc_hour, dtype: float64

In [6]:
# response_train = pp_data_train[['row_id', 'incident_id', 'vehicle_id', 'occupant_id', 'injury']]
# response_train.head()

In [7]:
# encoding = {'Unharmed': 0, 'Possible': 1, 'Minor': 2, 'Major': 3, 'Fatal': 4}

# response_train['injury'] = response_train['injury'].map(encoding)
# response_train.head()

In [8]:
# pp_data_train.select_dtypes(include = ['object']).T

In [9]:
# pp_data_train.select_dtypes(exclude = ['object']).T

In [10]:
# cols = ['drv_ban1_mo', 'drv_ban1_yr', 'drv_ban2_mo', 'drv_ban2_yr']

# for col in cols:
#     print('Column name: ', col)
#     print(pp_data_train[col].value_counts(dropna = False))
#     print('\n')

In [44]:
encoding_mon = {'Jan.': 1, 'Feb.': 2, 'Mar.': 3, 'Apr.': 4, 'May': 5, 'June': 6, 'July': 7, 'Aug.': 8, 
               'Sept.': 9, 'Oct.': 10, 'Nov.': 11, 'Dec.': 12, 'No record': np.nan, 'unknow': np.nan}

encoding_yr = {'No record': np.nan, 'unknown': np.nan, '2007': 2007, '2008': 2008, '2009': 2009, '2010': 2010, 
              '2011': 2011, '2012': 2012, '2013': 2013, '2014': 2014}

In [11]:
# pp_data_train['drv_ban1_mo'].map(encoding_mon).value_counts(dropna = False)

In [32]:
pp_data_train['drv_ban1_mo'] = pp_data_train['drv_ban1_mo'].map(encoding_mon)
pp_data_train['drv_ban2_mo'] = pp_data_train['drv_ban2_mo'].map(encoding_mon)

In [46]:
pp_data_train['drv_ban1_yr'] = pp_data_train['drv_ban1_yr'].map(encoding_yr)
pp_data_train['drv_ban2_yr'] = pp_data_train['drv_ban2_yr'].map(encoding_yr)

In [52]:
# gererate 2 new features

pp_data_train['inc_ban1_time'] = (pp_data_train['inc_datetime'].dt.year - pp_data_train['drv_ban1_yr'])*12 + (pp_data_train['inc_datetime'].dt.month - pp_data_train['drv_ban1_mo'])
pp_data_train['inc_ban2_time'] = (pp_data_train['inc_datetime'].dt.year - pp_data_train['drv_ban2_yr'])*12 + (pp_data_train['inc_datetime'].dt.month - pp_data_train['drv_ban2_mo'])

In [55]:
pp_data_train['veh_age_new'] = pp_data_train['inc_datetime'].dt.year - pp_data_train['veh_year']

In [56]:
pp_data_train['veh_age_new'].head()

0    9.0
1    9.0
2    7.0
3    7.0
4    8.0
Name: veh_age_new, dtype: float64

In [57]:
pp_data_train.drop(['injury', 'inc_datetime', 'drv_ban1_mo', 'drv_ban1_yr', 'drv_ban2_mo', 'drv_ban2_yr'], axis =1, inplace = True)

In [12]:
# # extract 2 features from incident_id
# df_driver = pp_data_train.loc[pp_data_train['occ_role'] == 'Driver', ['row_id', 'incident_id', 'occ_age']]
# df_driver.head()

In [123]:
df_driver.shape

(96541, 3)

In [124]:
len(set(df_driver['incident_id']))

63907

In [82]:
df_driver_min = pd.DataFrame(df_driver.groupby(['incident_id'])['occ_age'].min())
df_driver_max = pd.DataFrame(df_driver.groupby(['incident_id'])['occ_age'].max())

In [83]:
df_driver_min.head()

occ_age
incident_id         
2                 75
4                 25
5                 37
11                18
14                22

In [84]:
df_driver_min.reset_index(inplace = True)
df_driver_max.reset_index(inplace = True)

In [85]:
df_driver_max.head()

incident_id  occ_age
0            2       75
1            4       29
2            5       58
3           11       49
4           14       80

In [86]:
df_driver_min.columns.values 

array(['incident_id', 'occ_age'], dtype=object)

In [87]:
df_driver_min.columns = ['incident_id', 'driver_age_min']
df_driver_max.columns = ['incident_id', 'driver_age_max']

In [13]:
# df_driver_min.head()

In [14]:
# df_driver_max.head()

In [90]:
print(len(df_driver_min))
print(len(df_driver_max))

63907
63907


In [15]:
# pp_data_train.T

In [100]:
df_all4train = pd.merge(pp_data_train, df_driver_max, left_on = 'incident_id', right_on = 'incident_id')

In [16]:
# df_all4train.T

In [102]:
df_all4train = pd.merge(df_all4train, df_driver_min, left_on = 'incident_id', right_on = 'incident_id')

In [17]:
# df_all4train.T

In [104]:
df_all4train.shape

(144683, 65)

In [106]:
pp_data_train.shape

(145063, 63)

In [107]:
len(np.unique(pp_data_train['incident_id']))

64149

In [108]:
len(set(pp_data_train['incident_id']))

64149

In [109]:
print(pp_data_train['incident_id'].min())
print(pp_data_train['incident_id'].max())

2
128188


In [110]:
pp_data_train['occ_age'].isnull().sum()

0

In [112]:
print(df_driver_min['incident_id'].min())
print(df_driver_min['incident_id'].max())

2
128188


In [114]:
print(len(np.unique(df_driver_min['incident_id'])))
print(df_driver_min.shape)

63907
(63907, 2)


In [1]:
# set(pp_data_train['incident_id']).difference(df_driver_min['incident_id'])

In [117]:
pp_data_train.loc[pp_data_train['incident_id'] == 242, 'occ_age']

287    23
Name: occ_age, dtype: int64

In [121]:
pp_data_train.loc[pp_data_train['incident_id'] == 520, 'occ_age']

552    41
553    22
554    21
555    23
Name: occ_age, dtype: int64

In [122]:
pp_data_train.groupby(['incident_id'])['occ_age'].max().shape

(64149,)

In [125]:
pp_data_train['occ_role'].value_counts(dropna = True)

Driver            96541
Passenger         47951
Not-in-transit      571
Name: occ_role, dtype: int64

In [126]:
df_driver_min.loc[df_driver_min['incident_id'] == 520, :]

Empty DataFrame
Columns: [incident_id, driver_age_min]
Index: []

In [128]:
df_driver.loc[df_driver['incident_id'] == 520, :]

Empty DataFrame
Columns: [row_id, incident_id, occ_age]
Index: []

In [18]:
# df_driver_2 = pp_data_train.loc[pp_data_train['occ_role'] == 'Driver', ['row_id', 'incident_id', 'occ_age']]
# df_driver_2.head()

In [130]:
df_driver_2.loc[df_driver_2['incident_id'] == 520, :]

Empty DataFrame
Columns: [row_id, incident_id, occ_age]
Index: []

In [131]:
pp_data_train.shape

(145063, 63)

In [19]:
# pp_data_train.T

In [133]:
pp_data_train['drv_status'].value_counts()

Clean         122547
Penalised      10318
No licence      8331
Expired         1873
unknown         1423
Name: drv_status, dtype: int64

In [141]:
pp_data_train['drv_status'].value_counts().index

Index(['Clean', 'Penalised', 'No licence', 'Expired', 'unknown'], dtype='object')

In [20]:
# pp_data_train.columns

In [145]:
#imputate missing values for both numerical and categorical features

for col_n in pp_data_train.select_dtypes(exclude = ['object']).columns:
    pp_data_train[col_n].fillna(pp_data_train[col_n].median(), inplace = True)
    
    
for col_c in pp_data_train.select_dtypes(include = ['object']).columns:
    pp_data_train[col_c].fillna(pp_data_train[col_c].value_counts().index[0], inplace = True)

In [21]:
# for col in pp_data_train.columns:
#     print('Column name: ', col)
#     print(pp_data_train[col].isnull().sum())
#     print('\n')

In [22]:
# pp_data_train.T

In [148]:
pp_data_train_2 = pd.get_dummies(pp_data_train)
pp_data_train_2.shape

(145063, 306)

In [23]:
# pp_data_train_2.T

In [169]:
samp_id = pp_data_train_2['incident_id']
len(np.unique(samp_id))

64149

In [170]:
samp_id = np.unique(samp_id)
print(len(samp_id))

64149


In [171]:
from sklearn.model_selection import train_test_split

index_train, index_valid = train_test_split(samp_id, test_size = 0.2, random_state = 123)

In [172]:
print(len(index_train))
print(len(index_valid))

51319
12830


In [24]:
# pp_data_train_2.set_index('incident_id', inplace = True)
# pp_data_train_2.head()

In [174]:
X_train = pp_data_train_2.loc[index_train]
X_valid = pp_data_train_2.loc[index_valid]

In [175]:
print(X_train.shape)
print(X_valid.shape)

(116269, 305)
(28794, 305)


In [25]:
# X_train.head()

In [177]:
X_train.reset_index(inplace = True)
X_valid.reset_index(inplace = True)

In [26]:
# X_train.head()

In [27]:
# X_valid.head()

In [180]:
X_train.sort_values(by = ['row_id'], inplace = True)

C:\Users\LUY1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
# X_train.head()

In [182]:
X_valid.sort_values(by = ['row_id'], inplace = True)

C:\Users\LUY1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [29]:
# X_valid.head()

In [196]:
X_train.drop(['incident_id', 'row_id', 'vehicle_id', 'occupant_id'], axis = 1, inplace = True)
X_valid.drop(['incident_id', 'row_id', 'vehicle_id', 'occupant_id'], axis = 1, inplace = True)

C:\Users\LUY1\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [30]:
# X_train.head()

In [31]:
# response_train.head()

In [185]:
response_train.set_index(['row_id'], inplace = True)

In [32]:
# response_train.head()

In [187]:
y_train = response_train.loc[X_train['row_id']]
y_valid = response_train.loc[X_valid['row_id']]

In [33]:
# y_train.head()

In [189]:
y_train = y_train['injury']
y_valid = y_valid['injury']

print(y_train.shape)
print(y_valid.shape)

(116269,)
(28794,)


In [190]:
X_train.to_pickle('X_train.pkl')
X_valid.to_pickle('X_valid.pkl')
y_train.to_pickle('y_train.pkl')
y_valid.to_pickle('y_valid.pkl')

In [191]:
y_train.head()

row_id
2     3
3     4
13    0
14    4
30    1
Name: injury, dtype: int64

In [34]:
# X_valid.head()

In [192]:
import lightgbm as lgb

lgbtrain = lgb.Dataset(X_train, label = y_train)
lgbvalid = lgb.Dataset(X_valid, label = y_valid)

In [193]:
params_1 = {'objective': 'multiclass',
          'num_class': 5,
         'metric': 'multi_logloss',
         'num_leaves': 31,
          'max_depth': 7,
         'learning_rate': 0.05,
         'feature_fraction': 0.9,
         'bagging_fraction': 0.8,
         'bagging_freq': 5,
         'verbose': 1}

In [198]:
mod_1 = lgb.train(params = params_1,
                 train_set = lgbtrain,
                 num_boost_round = 5000,
                 valid_sets = [lgbtrain, lgbvalid],
                 early_stopping_rounds = 50,
                 verbose_eval = 40)

Training until validation scores don't improve for 50 rounds.
[40]	training's multi_logloss: 1.00964	valid_1's multi_logloss: 1.01406
[80]	training's multi_logloss: 0.919926	valid_1's multi_logloss: 0.932829
[120]	training's multi_logloss: 0.88341	valid_1's multi_logloss: 0.906626
[160]	training's multi_logloss: 0.859365	valid_1's multi_logloss: 0.893245
[200]	training's multi_logloss: 0.840494	valid_1's multi_logloss: 0.884967
[240]	training's multi_logloss: 0.824945	valid_1's multi_logloss: 0.879441
[280]	training's multi_logloss: 0.811747	valid_1's multi_logloss: 0.875976
[320]	training's multi_logloss: 0.799274	valid_1's multi_logloss: 0.872806
[360]	training's multi_logloss: 0.788179	valid_1's multi_logloss: 0.870721
[400]	training's multi_logloss: 0.777972	valid_1's multi_logloss: 0.868907
[440]	training's multi_logloss: 0.767872	valid_1's multi_logloss: 0.867536
[480]	training's multi_logloss: 0.75838	valid_1's multi_logloss: 0.866969
[520]	training's multi_logloss: 0.749674	val

In [200]:
params_2 = {'num_leaves': 54,
           'min_data_in_leaf': 79,
           'objective': 'multiclass',
           'num_class': 5,
           'metric': 'multi_logloss',
           'max_depth': -1,
           'learning_rate': 0.01,
           'boosting': 'gbdt',
           'feature_fraction': 0.9,
         'bagging_fraction': 0.8,
         'bagging_freq': 5,
         'verbosity': -1,
           'reg_alpha': 1.13,
           'reg_lambda': 0.36}

In [202]:
mod_2 = lgb.train(params = params_2,
                 train_set = lgbtrain,
                 num_boost_round = 5000,
                 valid_sets = [lgbtrain, lgbvalid],
                 early_stopping_rounds = 50,
                 verbose_eval = 40)

Training until validation scores don't improve for 50 rounds.
[40]	training's multi_logloss: 1.33434	valid_1's multi_logloss: 1.33608
[80]	training's multi_logloss: 1.18284	valid_1's multi_logloss: 1.18721
[120]	training's multi_logloss: 1.08873	valid_1's multi_logloss: 1.09564
[160]	training's multi_logloss: 1.02706	valid_1's multi_logloss: 1.03674
[200]	training's multi_logloss: 0.984574	valid_1's multi_logloss: 0.99726
[240]	training's multi_logloss: 0.954225	valid_1's multi_logloss: 0.969716
[280]	training's multi_logloss: 0.931455	valid_1's multi_logloss: 0.949905
[320]	training's multi_logloss: 0.913997	valid_1's multi_logloss: 0.935325
[360]	training's multi_logloss: 0.899723	valid_1's multi_logloss: 0.924116
[400]	training's multi_logloss: 0.887864	valid_1's multi_logloss: 0.915493
[440]	training's multi_logloss: 0.877833	valid_1's multi_logloss: 0.908672
[480]	training's multi_logloss: 0.86886	valid_1's multi_logloss: 0.903194
[520]	training's multi_logloss: 0.861068	valid_1's

In [35]:
# pp_data_train_2.head()

In [36]:
# pp_data_train_2.reset_index(inplace = True)
# pp_data_train_2.head()

In [210]:
pp_data_train_2.drop(['index'], axis = 1, inplace = True)

In [37]:
# pp_data_train_2.head()

In [38]:
# pp_data_train_2.sort_values(by = ['row_id'], inplace = True)
# pp_data_train_2.head()

In [39]:
# response_train.head()

In [221]:
response_train.reset_index(inplace = True)

In [40]:
# response_train.head()

In [41]:
# y_train = response_train[['row_id', 'injury']]
# y_train.head()

In [224]:
y_train.sort_values(by = ['row_id'], inplace = True)

C:\Users\LUY1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [42]:
# y_train.head()

In [226]:
y_train.drop(['row_id'], axis = 1, inplace = True)

C:\Users\LUY1\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [43]:
# y_train.head()

In [228]:
from sklearn.model_selection import GroupKFold

folds_split = list(GroupKFold(n_splits = 5).split(pp_data_train_2,
                                                 groups = pp_data_train_2.loc[:, 'incident_id']))

In [229]:
folds_split

[(array([     0,      1,      5, ..., 145060, 145061, 145062]),
  array([     2,      3,      4, ..., 145048, 145049, 145059])),
 (array([     0,      1,      2, ..., 145060, 145061, 145062]),
  array([    16,     17,     46, ..., 145056, 145057, 145058])),
 (array([     0,      1,      2, ..., 145058, 145059, 145060]),
  array([     7,      8,      9, ..., 145055, 145061, 145062])),
 (array([     2,      3,      4, ..., 145060, 145061, 145062]),
  array([     0,      1,      5, ..., 145034, 145035, 145036])),
 (array([     0,      1,      2, ..., 145059, 145061, 145062]),
  array([    30,     32,     33, ..., 145051, 145052, 145060]))]

In [230]:
pp_data_train_cv = pp_data_train_2.drop(['incident_id', 'row_id', 'vehicle_id', 'occupant_id'], axis = 1)

In [44]:
# pp_data_train_cv.head()

In [232]:
lgb_data = lgb.Dataset(pp_data_train_cv, label = y_train)

In [234]:
params_3 = {'num_leaves': 54,
           'min_data_in_leaf': 79,
           'objective': 'multiclass',
           'num_class': 5,
           'metric': 'multi_logloss',
           'max_depth': -1,
           'learning_rate': 0.01,
           'boosting': 'gbdt',
           'feature_fraction': 0.9,
         'bagging_fraction': 0.8,
         'bagging_freq': 5,
         'verbosity': 200,
           'reg_alpha': 1.13,
           'reg_lambda': 0.36}

In [235]:
mod_3 = lgb.cv(params = params_3,
              num_boost_round = 5000,
              verbose_eval = 200,
              train_set = lgb_data,
              early_stopping_rounds = 100,
              folds = folds_split)

[200]	cv_agg's multi_logloss: 1.00119 + 0.0054342
[400]	cv_agg's multi_logloss: 0.920109 + 0.00696646
[600]	cv_agg's multi_logloss: 0.895596 + 0.00726214
[800]	cv_agg's multi_logloss: 0.884098 + 0.00731785
[1000]	cv_agg's multi_logloss: 0.877694 + 0.00743688
[1200]	cv_agg's multi_logloss: 0.873655 + 0.00738876
[1400]	cv_agg's multi_logloss: 0.870915 + 0.00750538
[1600]	cv_agg's multi_logloss: 0.869105 + 0.00734316
[1800]	cv_agg's multi_logloss: 0.867939 + 0.00735443
[2000]	cv_agg's multi_logloss: 0.867109 + 0.00728805
[2200]	cv_agg's multi_logloss: 0.866478 + 0.00733958
[2400]	cv_agg's multi_logloss: 0.866042 + 0.00727929
[2600]	cv_agg's multi_logloss: 0.865653 + 0.00727215
[2800]	cv_agg's multi_logloss: 0.865458 + 0.00722573
[3000]	cv_agg's multi_logloss: 0.865393 + 0.00715877
