In [1]:
import pandas as pd
import numpy as np

In [1]:
# df = pd.read_csv('pp_data_train.csv')
# print(df.shape)

In [2]:
# df.head(7)

In [3]:
# col_n1 = df.select_dtypes(include = ['object']).columns.values
# col_n2 = df.select_dtypes(exclude = ['object']).columns.values

# print(len(col_n1))
# print(col_n1)

# print(len(col_n2))
# print(col_n2)

In [4]:
# print(df.columns.values)

In [5]:
# for col in df.columns.values:
#     print('Column name: ', col)
#     print('Missing value counts: ', df[col].isnull().sum())
#     print('\n')

In [6]:
# inc_datetime

# df['inc_datetime'] = pd.to_datetime(df['inc_datetime'])
# df['inc_datetime']

In [33]:
df['inc_datetime'].isnull().sum()

571

In [34]:
df['inc_datetime'].isnull().astype(int).sum()

571

In [35]:
df['inc_datetime_isnull'] = df['inc_datetime'].isnull().astype(int)

In [36]:
df['inc_datetime_mon'] = df['inc_datetime'].dt.month
df['inc_datetime_hour'] = df['inc_datetime'].dt.hour

In [37]:
df['inc_datetime_hour'].isnull().sum()

571

In [38]:
# inc_day

df['inc_day'].isnull().sum()

0

In [1]:
# df['inc_day'].value_counts()

In [2]:
# # inc_daylight

# print(df['inc_daylight'].isnull().sum())

# print(df['inc_daylight'].value_counts())

In [7]:
# l_null = [1 if cat in ['unknown'] else 0 for cat in df['inc_daylight']]
# print(l_null)

In [42]:
sum(l_null)

406

In [3]:
# df['inc_daylight_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_daylight']]
# df['inc_daylight_isnull'].head()

In [44]:
df['inc_daylight_isnull'].sum()

406

In [4]:
# # inc_weather

# print(df['inc_weather'].isnull().sum())

# print(df['inc_weather'].value_counts())

In [5]:
# df['inc_weather_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_weather']]
# df['inc_weather_isnull'].head()

In [47]:
df['inc_weather_isnull'].sum()

4650

In [6]:
# # veh_roadcond

# print(df['veh_roadcond'].isnull().sum())

# print(df['veh_roadcond'].value_counts())

In [50]:
df['veh_roadcond_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_roadcond']]

In [7]:
# df['veh_roadcond_isnull'].head()

In [8]:
# # veh_roadslope

# print(df['veh_roadslope'].isnull().sum())
# print(df['veh_roadslope'].value_counts())

In [9]:
# df['veh_roadslope_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_roadslope']]
# df['veh_roadslope_isnull'].head()

In [55]:
df['veh_roadslope_isnull'].sum()

10650

In [10]:
# # veh_lanediv

# print(df['veh_lanediv'].isnull().sum())
# print(df['veh_lanediv'].value_counts())

In [11]:
# df['veh_lanediv_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_lanediv']]
# df['veh_lanediv_isnull'].head()

In [12]:
# # occ_sex

# print(df['occ_sex'].isnull().sum())
# print(df['occ_sex'].value_counts())

In [13]:
# # occ_role

# print(df['occ_role'].isnull().sum())
# print(df['occ_role'].value_counts())

In [14]:
# # occ_position

# print(df['occ_position'].isnull().sum())
# print(df['occ_position'].value_counts())

In [62]:
df['occ_position_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['occ_position']]

In [15]:
# # occ_seatbelt

# print(df['occ_seatbelt'].isnull().sum())
# print(df['occ_seatbelt'].value_counts())

In [64]:
df['occ_seatbelt_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['occ_seatbelt']]
print(df['occ_seatbelt_isnull'].sum())

13828


In [16]:
# #occ_airbag

# print(df['occ_airbag'].isnull().sum())
# print(df['occ_airbag'].value_counts())

In [67]:
df['occ_airbag_isnull'] = [1 if cat in  ['unknown'] else 0 for cat in df['occ_airbag']]

print(df['occ_airbag_isnull'].sum())

32030


In [17]:
# # occ_alcohol

# print(df['occ_alcohol'].isnull().sum())
# print(df['occ_alcohol'].value_counts())

In [69]:
df['occ_alcohol_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['occ_alcohol']]

print(df['occ_alcohol_isnull'].sum())

68474


In [18]:
# # veh_owner

# print(df['veh_owner'].isnull().sum())
# print(df['veh_owner'].value_counts())

In [72]:
df['veh_owner_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_owner']]
print(df['veh_owner_isnull'].sum())

5046


In [19]:
# # veh_type

# print(df['veh_type'].isnull().sum())
# print(df['veh_type'].value_counts())

In [8]:
# veh_style

# print(df['veh_style'].isnull().sum())
# print(df['veh_style'].value_counts(dropna = False))

In [76]:
isnull(np.nan)

NameError: name 'isnull' is not defined

In [78]:
np.isnan(np.nan)

True

In [82]:
l = [1 if cat in [np.nan] else 0 for cat in df['veh_style']]

In [83]:
sum(l)

3298

In [87]:
df['veh_style_isnull'] = [1 if cat in [np.nan] else 0 for cat in df['veh_style']]
print(df['veh_style_isnull'].sum())

3298


In [20]:
# # veh_weight

# print(df['veh_weight'].isnull().sum())
# print(df['veh_weight'].value_counts(dropna  =False))

In [88]:
df['veh_weight_isnull'] = [1 if cat in [np.nan] else 0 for cat in df['veh_weight']]
print(df['veh_weight_isnull'].sum())

133408


In [9]:
# veh_manu

# print(df['veh_manu'].isnull().sum())
# print(df['veh_manu'].value_counts(dropna = False))

In [91]:
df['veh_manu_isnull'] = [1 if cat in [np.nan] else 0 for cat in df['veh_manu']]

print(df['veh_manu_isnull'].sum())

6911


In [21]:
# # veh_drive

# print(df['veh_drive'].isnull().sum())
# print(df['veh_drive'].value_counts(dropna = False))

In [93]:
df['veh_drive_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_drive']]

print(df['veh_drive_isnull'].sum())

14796


In [22]:
# # veh_fuel

# print(df['veh_fuel'].isnull().sum())
# print(df['veh_fuel'].value_counts())

In [95]:
df['veh_fuel_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_fuel']]

print(df['veh_fuel_isnull'].sum())

14681


In [23]:
# # veh_trailer

# print(df['veh_trailer'].isnull().sum())
# print(df['veh_trailer'].value_counts())

In [24]:
# # drv_licence

# print(df['drv_licence'].isnull().sum())
# print(df['drv_licence'].value_counts())

In [98]:
df['drv_licence_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['drv_licence']]
print(df['drv_licence_isnull'].sum())

1961


In [25]:
# # drv_status

# print(df['drv_status'].isnull().sum())
# print(df['drv_status'].value_counts(dropna = False))

In [101]:
l = [1 if cat in ['unknown', np.nan] else 0 for cat in df['drv_status']]
sum(l)

1994

In [103]:
df['drv_status_isnull'] = [1 if cat in ['unknown', np.nan] else 0 for cat in df['drv_status']]

print(df['drv_status_isnull'].sum())

1994


In [10]:
# drv_ban1_mo

# print(df['drv_ban1_mo'].isnull().sum())
# print(df['drv_ban1_mo'].value_counts())

In [108]:
df['drv_ban1_mo_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban1_mo']]
print(df['drv_ban1_mo_isnull'].sum())

83987


In [26]:
# encoding = {'Jan.': 1, 'Feb.': 2, 'Mar.': 3, 'Apr.': 4, 'May': 5, 'June': 6, 'July': 7, 'Aug.': 8,
#            'Sept.': 9, 'Oct.': 10, 'Nov.': 11, 'Dec.': 12, 'No record': np.nan, 'unknown': np.nan}

# df['drv_ban1_mo_num'] = df['drv_ban1_mo'].map(encoding)

# print(df['drv_ban1_mo_num'].value_counts())

In [11]:
# drv_ban1_yr

# print(df['drv_ban1_yr'].isnull().sum())
# print(df['drv_ban1_yr'].value_counts(dropna = False))

In [112]:
df['drv_ban1_yr_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban1_yr']]
print(df['drv_ban1_yr_isnull'].sum())

83984


In [27]:
# encoding = {'2007': 2007, '2008': 2008, '2009': 2009, '2010': 2010, '2011': 2011, '2012': 2012, '2013': 2013,
#            '2014': 2014, 'No record': np.nan, 'unknown': np.nan}

# df['drv_ban1_yr_num'] = df['drv_ban1_yr'].map(encoding)

# print(df['drv_ban1_yr_num'].value_counts(dropna = False))

In [28]:
# # drv_ban2_mo

# print(df['drv_ban2_mo'].isnull().sum())
# print(df['drv_ban2_mo'].value_counts(dropna = False))

In [115]:
df['drv_ban2_mo_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban2_yr']]
print(df['drv_ban2_mo_isnull'].sum())

83983


In [29]:
# encoding = {'Jan.': 1, 'Feb.': 2, 'Mar.': 3, 'Apr.': 4, 'May': 5, 'June': 6, 'July': 7, 'Aug.': 8,
#            'Sept.': 9, 'Oct.': 10, 'Nov.': 11, 'Dec.': 12, 'No record': np.nan, 'unknown': np.nan}

# df['drv_ban2_mo_num'] = df['drv_ban2_mo'].map(encoding)

# print(df['drv_ban2_mo_num'].value_counts())

In [30]:
# # drv_ban2_yr

# print(df['drv_ban2_yr'].isnull().sum())
# print(df['drv_ban2_yr'].value_counts(dropna = False))

In [119]:
df['drv_ban2_yr_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban2_yr']]
print(df['drv_ban2_yr_isnull'].sum())

83983


In [31]:
# encoding = {'2007': 2007, '2008': 2008, '2009': 2009, '2010': 2010, '2011': 2011, '2012': 2012, '2013': 2013,
#            '2014': 2014, 'No record': np.nan, 'unknown': np.nan}

# df['drv_ban2_yr_num'] = df['drv_ban2_yr'].map(encoding)

# print(df['drv_ban2_yr_num'].value_counts(dropna = False))

In [32]:
# #drv_alcohol

# print(df['drv_alcohol'].isnull().sum())
# print(df['drv_alcohol'].value_counts(dropna = False))

In [33]:
# # inc_type

# print(df['inc_type'].isnull().sum())
# print(df['inc_type'].value_counts(dropna = False))

In [126]:
df['inc_type_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_type']]
print(df['inc_type_isnull'].sum())

22153


In [34]:
# # inc_speeding

# print(df['inc_speeding'].isnull().sum())
# print(df['inc_speeding'].value_counts(dropna = False))

In [129]:
df['inc_speeding_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_speeding']]
print(df['inc_speeding_isnull'].sum())

5736


In [35]:
# # veh_braking

# print(df['veh_braking'].isnull().sum())
# print(df['veh_braking'].value_counts(dropna = False))

In [131]:
df['veh_braking_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_braking']]
print(df['veh_braking_isnull'].sum())

73000


In [36]:
# # veh_stability

# print(df['veh_stability'].isnull().sum())
# print(df['veh_stability'].value_counts(dropna = False))

In [134]:
df['veh_stability_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_stability']]
print(df['veh_stability_isnull'].sum())

47087


In [37]:
# # veh_movement

# print(df['veh_movement'].isnull().sum())
# print(df['veh_movement'].value_counts(dropna = True))

In [136]:
df['veh_movement_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_movement']]
print(df['veh_movement_isnull'].sum())

38653


In [38]:
# # veh_impact

# print(df['veh_impact'].isnull().sum())
# print(df['veh_impact'].value_counts())

In [139]:
df['veh_impact_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_impact']]

print(df['veh_impact_isnull'].sum())

5452


In [39]:
# # inc_descrip

# print(df['inc_descrip'].isnull().sum())
# print(df['inc_descrip'].value_counts())

In [142]:
df['inc_descrip_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_descrip']]
print(df['inc_descrip_isnull'].sum())

34


In [40]:
# # veh_descrip

# print(df['veh_descrip'].isnull().sum())
# print(df['veh_descrip'].value_counts())

In [145]:
df['veh_descrip_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_descrip']]
print(df['veh_descrip_isnull'].sum())

635


In [41]:
# # veh_damage

# print(df['veh_damage'].isnull().sum())
# print(df['veh_damage'].value_counts())

In [147]:
df['veh_damage_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_damage']]
print(df['veh_damage_isnull'].sum())

9400


In [148]:
# numerical features

In [149]:
# total_veh_in_inc

df['total_veh_in_inc'].isnull().sum()

0

In [150]:
sum(df['total_veh_in_inc'] == -1)

0

In [152]:
# total_occ_in_inc

df['total_occ_in_veh'].isnull().sum()

0

In [153]:
sum(df['total_occ_in_veh'] == -1)

0

In [154]:
# actual_veh_in_inc

df['actual_veh_in_inc'].isnull().sum()

0

In [156]:
sum(df['actual_veh_in_inc'] == -1)

0

In [157]:
# actual_per_in_inc

df['actual_per_in_inc'].isnull().sum()

0

In [158]:
sum(df['actual_per_in_inc'] == -1)

0

In [159]:
# actual_occ_in_veh

df['actual_occ_in_veh'].isnull().sum()

0

In [160]:
sum(df['actual_occ_in_veh'] == -1)

0

In [161]:
# actual_ped

df['actual_ped'].isnull().sum()

0

In [162]:
sum(df['actual_ped'] == -1)

0

In [42]:
# # inc_region

# df['inc_region'].head()

In [164]:
df['inc_region'].isnull().sum()

0

In [165]:
sum(df['inc_region'] == -1)

0

In [166]:
# veh_lanes

df['veh_lanes'].isnull().sum()

0

In [167]:
sum(df['veh_lanes'] == -1)

1402

In [43]:
# l = [1 if num == -1 else 0 for num in df['veh_lanes']]
# print(sum(l))
# print(l[:5])

In [171]:
df['veh_lanes_isnull'] = [1 if num == -1 else 0 for num in df['veh_lanes']]

In [172]:
# veh_speedlim

print(df['veh_speedlim'].isnull().sum())

0


In [173]:
sum(df['veh_speedlim'] == -1)

5383

In [174]:
df['veh_speedlim_isnull'] = [1 if num == -1 else 0 for num in df['veh_speedlim']]

In [175]:
sum(df['veh_speedlim_isnull'])

5383

In [176]:
#occ_age

df['occ_age'].isnull().sum()

0

In [177]:
sum(df['occ_age'] == -1)

577

In [180]:
df['occ_age_isnull'] = [1 if num == -1 else 0 for num in df['occ_age']]

In [181]:
sum(df['occ_age_isnull'])

577

In [183]:
#veh_age

df['veh_year'].isnull().sum()

0

In [184]:
sum(df['veh_year'] == -1)

758

In [186]:
df['veh_year_isnull'] = [1 if num == -1 else 0 for num in df['veh_year']]

print(sum(df['veh_year_isnull']))

758


In [187]:
# veh_doors

df['veh_doors'].isnull().sum()

0

In [188]:
sum(df['veh_doors'] == -1)

3298

In [190]:
df['veh_doors_isnull'] = [1 if num == -1 else 0 for num in df['veh_doors']]

print(sum(df['veh_doors_isnull']))

3298


In [191]:
#veh_wheels

print(df['veh_wheels'].isnull().sum())
print(sum(df['veh_wheels'] == -1))

0
47927


In [192]:
df['veh_wheels_isnull'] = [1 if num == -1 else 0 for num in df['veh_wheels']]
print(sum(df['veh_wheels_isnull']))

47927


In [194]:
# veh_eng1

print(df['veh_eng1'].isnull().sum())
print(sum(df['veh_eng1'] == -1))

0
18435


In [195]:
df['veh_eng1_isnull'] = [1 if num == -1 else 0 for num in df['veh_eng1']]

print(sum(df['veh_eng1_isnull']))

18435


In [196]:
#veh_eng2

print(df['veh_eng2'].isnull().sum())
print(sum(df['veh_eng2'] == -1))

0
3617


In [197]:
df['veh_eng2_isnull'] = [1 if num == -1 else 0 for num in df['veh_eng2']]

print(sum(df['veh_eng2_isnull']))

3617


In [198]:
# drv_height

print(df['drv_height'].isnull().sum())
print(sum(df['drv_height'] == -1))

0
20385


In [199]:
df['drv_height_isnull'] = [1 if num == -1 else 0 for num in df['drv_height']]

print(sum(df['drv_height_isnull']))

20385


In [200]:
#drv_weight

print(df['drv_weight'].isnull().sum())
print(sum(df['drv_weight'] == -1))

0
50726


In [201]:
df['drv_weight_isnull'] = [1 if num == -1 else 0 for num in df['drv_weight']]

print(sum(df['drv_weight_isnull']))

50726


In [202]:
# drv_crash

print(df['drv_crash'].isnull().sum())
print(sum(df['drv_crash'] == -1))

0
15605


In [203]:
df['drv_crash_isnull'] = [1 if num == -1 else 0 for num in df['drv_crash']]

print(sum(df['drv_crash_isnull']))

15605


In [204]:
# drv_pts

print(df['drv_pts'].isnull().sum())
print(sum(df['drv_pts'] == -1))

0
3253


In [205]:
df['drv_pts_isnull'] = [1 if num == -1 else 0 for num in df['drv_pts']]
print(sum(df['drv_pts_isnull']))

3253


In [206]:
# drv_dui

print(df['drv_dui'].isnull().sum())
print(sum(df['drv_dui'] == -1))

0
3253


In [207]:
df['drv_dui_isnull'] = [1 if num == -1 else 0 for num in df['drv_dui']]
print(sum(df['drv_dui_isnull']))

3253


In [210]:
# drv_spd

print(df['drv_spd'].isnull().sum())
print(sum(df['drv_spd'] == -1))

0
3253


In [209]:
df['drv_spd_isnull'] = [1 if num == -1 else 0 for num in df['drv_spd']]

print(sum(df['drv_spd_isnull']))

3253


In [211]:
#veh_speed

print(df['veh_speed'].isnull().sum())
print(sum(df['veh_speed'] == -1))

0
88909


In [212]:
df['veh_speed_isnull'] = [1 if num == -1 else 0 for num in df['veh_speed']]
print(sum(df['veh_speed_isnull']))

88909


In [12]:
# df.head()

In [214]:
df.shape

(145063, 117)

In [13]:
# df.T

In [217]:
df.to_pickle('pp_train_isnull_1.pkl')

In [14]:
#calculate missing value counts for categorical features
# pd.set_option('display.max_rows', 120)


# df.isnull().sum()

In [15]:
# df.select_dtypes(include = ['object']).isnull().sum()

In [44]:
# df['veh_type'].value_counts(dropna = False)

In [222]:
# fill missing values(NANs) for categorical features
# veh_type

df['veh_type'].fillna('unknown', inplace = True)

In [45]:
# print(df['veh_type'].isnull().sum())
# print(df['veh_type'].value_counts(dropna = False))

In [16]:
#veh_style

# df['veh_style'].fillna('unknown', inplace = True)

# print(df['veh_style'].isnull().sum())
# print(df['veh_style'].value_counts(dropna = False))

In [46]:
# # veh_weight

# df['veh_weight'].fillna('unknown', inplace = True)

# print(df['veh_weight'].isnull().sum())
# print(df['veh_weight'].value_counts())

In [17]:
# veh_manu

# df['veh_manu'].fillna('unknown', inplace = True)

# print(df['veh_manu'].isnull().sum())
# print(df['veh_manu'].value_counts(dropna = False))

In [47]:
# # drv_status

# df['drv_status'].fillna('unknown', inplace = True)

# print(df['drv_status'].isnull().sum())
# print(df['drv_status'].value_counts(dropna = False))

In [18]:
# df.select_dtypes(include = ['object']).isnull().sum()

In [230]:
df.to_pickle('pp_train_isnull_2.pkl')

In [19]:
# do feature engineering

# df.T

In [233]:
#inc_datetime

df['inc_datetime_yr'] = df['inc_datetime'].dt.year

In [234]:
df.to_pickle('pp_train_isnull_3.pkl')

In [236]:
#new feature: veh_age = inc_datetime_yr - veh_+year

df['veh_age'] = df['inc_datetime_yr'] - df['veh_year']

In [245]:
#new feature_1: drv_ban1 = (inc_datetime_yr-drv_ban1_yr)*12+(inc_datetime_mon-drv_ban1_mo)
#new feature_2: dfv_ban2 = (inc_datetime_yr-drv_ban2_yr)*12+(inc_datetime_mon-drv_ban2_mo)

df['drv_ban1_num'] = (df['inc_datetime_yr']-df['drv_ban1_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban1_mo_num'])
df['drv_ban2_num'] = (df['inc_datetime_yr']-df['drv_ban2_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban2_mo_num'])

In [20]:
# (df['inc_datetime_yr']-df['drv_ban1_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban1_mo_num'])

In [21]:
# (df['inc_datetime_yr']-df['drv_ban2_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban2_mo_num'])

In [22]:
# df['drv_ban1_yr_num'].value_counts(dropna = False)

In [246]:
df.to_pickle('pp_train_isnull_4.pkl')

In [23]:
# df = pd.read_pickle('pp_train_isnull_4.pkl')
# df.head()

In [24]:
# df.T

In [25]:
# df.T

In [26]:
# df.info()

In [27]:
# pd.set_option('display.max_rows', 200)

# df.dtypes

In [9]:
df.drop(['inc_datetime', 'drv_ban1_mo', 'drv_ban1_yr', 'drv_ban2_mo', 'drv_ban2_yr'], axis = 1, inplace = True)

In [28]:
# df.T

In [11]:
df.drop(['veh_year'], axis = 1, inplace = True)

In [29]:
# df.select_dtypes(include = ['object']).T

In [30]:
# encoding = {'Unharmed': 0, 'Possible': 1, 'Minor': 2, 'Major': 3, 'Fatal': 4}

# y = df['injury'].map(encoding)
# print(y)

In [14]:
df.drop(['injury'], axis = 1, inplace = True)

In [31]:
# df.T

In [32]:
# X = pd.get_dummies(df)
# X.head()

In [33]:
# X.T

In [18]:
from sklearn.model_selection import GroupKFold

folds_split = list(GroupKFold(n_splits = 5).split(X,
                                                 groups = X.loc[:, 'incident_id']))

In [19]:
folds_split

[(array([     0,      1,      5, ..., 145060, 145061, 145062]),
  array([     2,      3,      4, ..., 145048, 145049, 145059])),
 (array([     0,      1,      2, ..., 145060, 145061, 145062]),
  array([    16,     17,     46, ..., 145056, 145057, 145058])),
 (array([     0,      1,      2, ..., 145058, 145059, 145060]),
  array([     7,      8,      9, ..., 145055, 145061, 145062])),
 (array([     2,      3,      4, ..., 145060, 145061, 145062]),
  array([     0,      1,      5, ..., 145034, 145035, 145036])),
 (array([     0,      1,      2, ..., 145059, 145061, 145062]),
  array([    30,     32,     33, ..., 145051, 145052, 145060]))]

In [20]:
folds_split[0]

(array([     0,      1,      5, ..., 145060, 145061, 145062]),
 array([     2,      3,      4, ..., 145048, 145049, 145059]))

In [21]:
folds_split[0][0]

array([     0,      1,      5, ..., 145060, 145061, 145062])

In [22]:
#further drop index columns: row_id, incident_id, vehicle_id, occupant_id

X.drop(['row_id', 'incident_id', 'vehicle_id', 'occupant_id'], axis = 1, inplace = True)

In [23]:
X.shape

(145063, 357)

In [24]:
import lightgbm as lgb

lgb_data = lgb.Dataset(X, label = y)

In [22]:
params_1 = {'num_leaves': 54,
           'min_data_in_leaf': 79,
           'objective': 'multiclass',
           'num_class': 5,
           'metric': 'multi_logloss',
           'max_depth': -1,
           'learning_rate': 0.01,
           'boosting': 'gbdt',
           'feature_fraction': 0.9,
         'bagging_fraction': 0.8,
         'bagging_freq': 5,
         'verbosity': 200,
           'reg_alpha': 1.13,
           'reg_lambda': 0.36}

In [278]:
mod_1 = lgb.cv(params = params_1,
              num_boost_round = 2000,
              verbose_eval = 200,
              train_set = lgb_data,
              early_stopping_rounds = 100,
              folds = folds_split)

[200]	cv_agg's multi_logloss: 1.00118 + 0.00535021
[400]	cv_agg's multi_logloss: 0.920033 + 0.00682481
[600]	cv_agg's multi_logloss: 0.8957 + 0.00707179
[800]	cv_agg's multi_logloss: 0.884286 + 0.00712488
[1000]	cv_agg's multi_logloss: 0.877915 + 0.00722648
[1200]	cv_agg's multi_logloss: 0.873992 + 0.00728572
[1400]	cv_agg's multi_logloss: 0.871379 + 0.00743518
[1600]	cv_agg's multi_logloss: 0.869527 + 0.00738668
[1800]	cv_agg's multi_logloss: 0.86838 + 0.0074462
[2000]	cv_agg's multi_logloss: 0.867527 + 0.0073764


In [23]:
import xgboost as xgb

In [24]:
dtrain = xgb.DMatrix(data = X, label = y)

In [25]:
params_2 = {'objective': 'multi:softprob',
            'eval_metric': ['mlogloss'],
            'num_class': 5,
            'colsample_bytree': 0.6,
           'gamma': 0.5,
           'learning_rate': 0.05,
           'max_depth': 7,
            'min_child_weight': 5,
            'lambda': 0.5,
            'alpha': 0.5,
           'n_estimators': 500,
           'subsample': 0.6}

In [26]:
mod2 = xgb.cv(params = params_2,
             dtrain = dtrain,
             num_boost_round = 300,
             early_stopping_rounds = 100,
             verbose_eval = 200,
             folds = folds_split)

[0]	train-mlogloss:1.56385+0.000358841	test-mlogloss:1.56442+0.000261794
[200]	train-mlogloss:0.79818+0.00154134	test-mlogloss:0.883665+0.00725878
[299]	train-mlogloss:0.752278+0.00151103	test-mlogloss:0.874351+0.00717486
